import { useEffect, useRef, useState } from 'react';
import api from '../services/api';
import { useI18n } from '../i18n';
import { affiliateUrl } from '../services/affiliate';

/**
 * Full-screen preview modal. Fetches the free preview pages for a book and
 * shows 15 key sentences (5 beginning, 5 middle, 5 end) generated by AI.
 * Displays book cover prominently.
 */
export default function BookPreviewModal({ book, highlightText, quoteId, onClose }) {
  const t = useI18n((s) => s.t);
  const lang = useI18n((s) => s.lang);
  const [data, setData] = useState(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(null);
  const [imgError, setImgError] = useState(false);
  const onCloseRef = useRef(onClose);
  useEffect(() => { onCloseRef.current = onClose; }, [onClose]);

  useEffect(() => {
    if (!book?.id) return;
    let active = true;
    setLoading(true);
    api
      .get(`/books/${book.id}/preview`, { params: { quoteId, lang } })
      .then((res) => {
        if (active) setData(res.data);
      })
      .catch((err) => active && setError(err.message))
      .finally(() => active && setLoading(false));
    return () => {
      active = false;
    };
  }, [book?.id, quoteId, lang]);

  useEffect(() => {
    function onEsc(e) {
      if (e.key === 'Escape') onCloseRef.current();
    }
    document.addEventListener('keydown', onEsc);
    document.body.style.overflow = 'hidden';
    return () => {
      document.removeEventListener('keydown', onEsc);
      document.body.style.overflow = '';
    };
  }, []);

  const pages = data?.previewPages || [];
  const affiliate = book?.id ? affiliateUrl(book.id, quoteId) : data?.affiliateLink || book?.affiliateLink;
  const cover = book?.coverImage;
  const isSentencePreview = data?.isSentencePreview || false;

  return (
    <div
      className="fixed inset-0 z-50 flex items-start justify-center overflow-y-auto overscroll-contain bg-black/70 p-0 backdrop-blur-sm sm:p-4"
      onClick={onClose}
    >
      <div
        className="min-h-full w-full max-w-3xl border-ink-600 bg-ink-800 shadow-2xl sm:my-8 sm:min-h-0 sm:rounded-2xl sm:border"
        onClick={(e) => e.stopPropagation()}
      >
        {/* Header with book info + cover */}
        <div className="sticky top-0 z-10 flex items-start justify-between gap-3 border-b border-ink-600 bg-ink-800/95 px-4 py-3 backdrop-blur sm:gap-4 sm:rounded-t-2xl sm:px-6 sm:py-4">
          <div className="flex min-w-0 items-center gap-3 sm:gap-4">
            {cover && !imgError ? (
              <img
                src={cover}
                alt={book?.title}
                className="h-16 w-11 flex-shrink-0 rounded-lg object-cover shadow-lg sm:h-20 sm:w-14"
                onError={() => setImgError(true)}
              />
            ) : (
              <div className="flex h-16 w-11 flex-shrink-0 items-center justify-center rounded-lg bg-ink-700 text-parchment-faint sm:h-20 sm:w-14">
                <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.5">
                  <path d="M4 5a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v16l-6-3-6 3z" />
                </svg>
              </div>
            )}
            <div className="min-w-0">
              <h3 className="font-display text-base leading-tight text-parchment sm:text-xl">{book?.title}</h3>
              <p className="truncate text-sm text-parchment-dim">{book?.author}</p>
              {book?.year && <p className="text-xs text-parchment-faint">{book.year}</p>}
            </div>
          </div>
          <button onClick={onClose} className="btn-ghost flex-shrink-0 px-3 py-1.5 text-sm" aria-label={t('preview.close')}>
            ✕
          </button>
        </div>

        {/* Content */}
        <div className="px-4 py-5 sm:px-6 sm:py-6">
          <p className="mb-4 text-xs uppercase tracking-wider text-amber flex items-center gap-2">
            {t('preview.title')}
            {isSentencePreview && (
              <span className="rounded-full bg-purple-900/50 px-2 py-0.5 text-xs text-purple-200">AI</span>
            )}
          </p>

          {loading && (
            <div className="space-y-3">
              {[...Array(6)].map((_, i) => (
                <div key={i} className="skeleton h-4 w-full" />
              ))}
            </div>
          )}

          {error && <p className="text-red-400">{error}</p>}

          {!loading && !error && pages.length === 0 && (
            <p className="text-parchment-dim text-center py-8">{t('search.empty')}</p>
          )}

          {!loading && !error && pages.length > 0 && isSentencePreview && (
            <div className="space-y-8">
              {/* Beginning */}
              <div>
                <h4 className="mb-3 font-semibold text-amber text-sm border-b border-ink-600 pb-2 uppercase tracking-wider flex items-center gap-2">
                  <span>📖</span> {t('preview.sentences.start')}
                </h4>
                <div className="space-y-3 pl-4 border-l-2 border-amber/30">
                  {pages.slice(0, 5).map((page, idx) => (
                    <p key={idx} className="font-body leading-relaxed text-parchment-dim italic text-sm">
                      “{page}”
                    </p>
                  ))}
                </div>
              </div>

              {/* Middle */}
              <div>
                <h4 className="mb-3 font-semibold text-amber text-sm border-b border-ink-600 pb-2 uppercase tracking-wider flex items-center gap-2">
                  <span>📖</span> {t('preview.sentences.middle')}
                </h4>
                <div className="space-y-3 pl-4 border-l-2 border-amber/30">
                  {pages.slice(5, 10).map((page, idx) => (
                    <p key={idx + 5} className="font-body leading-relaxed text-parchment-dim italic text-sm">
                      “{page}”
                    </p>
                  ))}
                </div>
              </div>

              {/* End */}
              <div>
                <h4 className="mb-3 font-semibold text-amber text-sm border-b border-ink-600 pb-2 uppercase tracking-wider flex items-center gap-2">
                  <span>📖</span> {t('preview.sentences.end')}
                </h4>
                <div className="space-y-3 pl-4 border-l-2 border-amber/30">
                  {pages.slice(10, 15).map((page, idx) => (
                    <p key={idx + 10} className="font-body leading-relaxed text-parchment-dim italic text-sm">
                      “{page}”
                    </p>
                  ))}
                </div>
              </div>
            </div>
          )}

          {!loading && !error && pages.length > 0 && !isSentencePreview && (
            <div className="space-y-4">
              {pages.map((page, idx) => (
                <p key={idx} className="font-body leading-relaxed text-parchment-dim text-sm">
                  {page}
                </p>
              ))}
            </div>
          )}

          {/* Buy CTA */}
          {!loading && affiliate && (
            <div className="mt-8 rounded-xl border border-ink-600 bg-ink-700 p-6 text-center">
              <p className="mb-2 font-display text-lg text-parchment">{t('preview.locked')}</p>
              <p className="mb-4 text-sm text-parchment-dim">{t('preview.locked.text')}</p>
              <a
                href={affiliate}
                target="_blank"
                rel="noopener noreferrer"
                className="btn-primary px-8 py-3"
              >
                {t('search.buy')}
              </a>
            </div>
          )}
        </div>
      </div>
    </div>
  );
}
